Repository appuio/component-openshift4-logging, pull requests merged in 2025-02, with the labels that each got.

#144 Update quay.io/appuio/oc Docker tag to v4.16
  class/defaults.yml
  tests/golden/defaults/openshift4-logging/openshift4-logging/50_fix_ingester_stuck.yaml
  tests/golden/master/openshift4-logging/openshift4-logging/50_fix_ingester_stuck.yaml
Labels: dependency

#168 Detect Multiline errors by default
  .cruft.json
  .github/workflows/test.yaml
  Makefile.vars.mk
  component/log_forwarder.libsonnet
  tests/golden/defaults/openshift4-logging/openshift4-logging/40_log_forwarder.yaml
  tests/golden/master/openshift4-logging/openshift4-logging/40_log_forwarder.yaml
  tests/golden/multilineerr/openshift4-logging/apps/openshift4-logging.yaml
  tests/golden/multilineerr/openshift4-logging/console-patching/openshift4_console_params.yaml
  tests/golden/multilineerr/openshift4-logging/openshift4-logging/00_namespace.yaml
  tests/golden/multilineerr/openshift4-logging/openshift4-logging/10_operator_group.yaml
  tests/golden/multilineerr/openshift4-logging/openshift4-logging/20_subscriptions.yaml
  tests/golden/multilineerr/openshift4-logging/openshift4-logging/40_log_forwarder.yaml
  tests/golden/multilineerr/openshift4-logging/openshift4-logging/40_log_forwarder_rbac.yaml
  tests/golden/multilineerr/openshift4-logging/openshift4-logging/60_collector_alerts.yaml
  tests/multilineerr.yml
Labels: change, bump:patch

#169 Fix initial sync by skipping dry-run for `UIPlugin`
  component/log_lokistack.libsonnet
  tests/golden/defaults/openshift4-logging/openshift4-logging/30_loki_plugin.yaml
  tests/golden/master/openshift4-logging/openshift4-logging/30_loki_plugin.yaml
Labels: bug, bump:patch

#170 Update cluster-observability-operator to stable/v1.x
  component/main.jsonnet
  tests/golden/defaults/openshift4-logging/openshift4-logging/20_subscriptions.yaml
  tests/golden/master/openshift4-logging/openshift4-logging/20_subscriptions.yaml
Labels: change, bump:patch
