Repository appuio/component-openshift4-logging, pull requests merged in 2025-01, with the labels that each got.

#161 Update from template
  .cruft.json
  class/defaults.yml
  class/openshift4-logging.yml
  component/app.jsonnet
Labels: template-sync

#163 Fix ClusterLogForwarder default pipelines
  component/log_forwarder.libsonnet
  tests/golden/defaults/openshift4-logging/openshift4-logging/40_log_forwarder.yaml
  tests/golden/master/openshift4-logging/openshift4-logging/40_log_forwarder.yaml
  tests/golden/multilineerr/openshift4-logging/openshift4-logging/40_log_forwarder.yaml
Labels: bug, bump:patch

#164 Fix Logs not sent to LokiStack
  component/log_forwarder.libsonnet
  tests/golden/defaults/openshift4-logging/openshift4-logging/40_log_forwarder.yaml
  tests/golden/defaults/openshift4-logging/openshift4-logging/40_log_forwarder_rbac.yaml
  tests/golden/master/openshift4-logging/openshift4-logging/40_log_forwarder.yaml
  tests/golden/master/openshift4-logging/openshift4-logging/40_log_forwarder_rbac.yaml
  tests/golden/multilineerr/openshift4-logging/openshift4-logging/40_log_forwarder.yaml
  tests/golden/multilineerr/openshift4-logging/openshift4-logging/40_log_forwarder_rbac.yaml
Labels: bug, bump:patch

#165 Fix generating null resource
  component/log_forwarder.libsonnet
  tests/golden/multilineerr/openshift4-logging/console-patching/openshift4_console_params.yaml
  tests/golden/multilineerr/openshift4-logging/openshift4-logging/20_subscriptions.yaml
  tests/golden/multilineerr/openshift4-logging/openshift4-logging/30_loki_logstore.yaml
  tests/golden/multilineerr/openshift4-logging/openshift4-logging/30_loki_netpol.yaml
  tests/golden/multilineerr/openshift4-logging/openshift4-logging/30_loki_plugin.yaml
  tests/golden/multilineerr/openshift4-logging/openshift4-logging/30_loki_rbac.yaml
  tests/golden/multilineerr/openshift4-logging/openshift4-logging/30_loki_stack.yaml
  tests/golden/multilineerr/openshift4-logging/openshift4-logging/40_log_forwarder.yaml
  tests/golden/multilineerr/openshift4-logging/openshift4-logging/40_log_forwarder_rbac.yaml
  tests/golden/multilineerr/openshift4-logging/openshift4-logging/50_fix_app_logs_reader.yaml
  tests/golden/multilineerr/openshift4-logging/openshift4-logging/50_fix_ingester_stuck.yaml
  tests/golden/multilineerr/openshift4-logging/openshift4-logging/50_fix_missing_metrics_token.yaml
  tests/golden/multilineerr/openshift4-logging/openshift4-logging/60_lokistack_alerts.yaml
  tests/multilineerr.yml
Labels: bug, bump:patch

#167 Document how to set log retention
  docs/modules/ROOT/pages/how-tos/enable-log-retention.adoc
  docs/modules/ROOT/partials/nav.adoc
Labels: documentation

#162 Update from template
  .cruft.json
Labels: template-sync
